name: test & maybe release

on:
  push:
    branches:
      - ${{{ github.default_branch }}}
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  js-test-and-release:
    uses: ipdxco/unified-github-workflows/.github/workflows/js-test-and-release.yml@${{{ .config.versions.uci // (.source.tag | sub("\\.[^\\.]+\\.[^\\.\\-\\+]+(?=\\-|\\+|$)"; "")) }}}
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      UCI_GITHUB_TOKEN: ${{ secrets.UCI_GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
      CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
      CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
      CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
