name: Copy Templates

on:
  workflow_dispatch:
    inputs:
      targets:
        description: "List of repository names to deploy to"
        required: true
      force:
        description: "Force copy even if file exists"
        required: false
      version:
        description: "Version to use for templates"
        required: false
      dry-run:
        description: "Whether to run in dry run mode"
        required: false
        default: 'false'

jobs:
  read-defaults:
    runs-on: ubuntu-latest
    outputs:
      defaults: ${{ steps.defaults.outputs.defaults }}
    steps:
      - uses: actions/checkout@v5
      - id: defaults
        name: Read defaults
        run: |
          echo "defaults<<EOF" >> $GITHUB_OUTPUT
          cat defaults.yml >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  copy-templates:
    needs: read-defaults
    uses: ./.github/workflows/process.yml
    secrets: inherit
    with:
      targets: ${{ github.event.inputs.targets }}
      branch: uci/copy-templates
      script: copy-templates.sh
      defaults: ${{ needs.read-defaults.outputs.defaults }}
      override: |
        force: ${{ github.event.inputs.force }}
        versions:
          uci: ${{ github.event.inputs.version }}
      dry-run: ${{ github.event.inputs.dry-run == 'true' }}
