name: Dispatch Run

on:
  workflow_dispatch:
    inputs:
      workflow:
        description: "Workflow to dispatch (e.g. .github/workflows/update-go.yml)"
        required: true
      inputs:
        description: 'Workflow inputs (e.g {"version": "1.25", "dry-run": "true"})'
        required: false
        default: '{}'
      filter:
        description: 'Filter to apply to the list of repositories (e.g. .language == "Go" and .owner.login == "ipdxco")'
        required: false
        default: 'true'
      dry-run:
        description: "Whether to run in dry run mode"
        required: false
        default: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write

jobs:
  dispatch:
    uses: ./.github/workflows/dispatch.yml
    secrets: inherit
    with:
      workflow: ${{ github.event.inputs.workflow }}
      inputs: ${{ github.event.inputs.inputs }}
      filter: ${{ github.event.inputs.filter }}
      dry-run: ${{ github.event.inputs.dry-run == 'true' }}
