name: Release
on:
  push:
    paths: [CHANGELOG.md]
    branches: [main, release/*]
  pull_request:
    paths: [CHANGELOG.md]
    branches: [main, release/*]
jobs:
  release:
    name: Realase
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - id: release
        uses: ipdxco/changelog-driven-release@v1
        with:
          path: CHANGELOG.md
          draft: ${{ github.event_name == 'pull_request' }}
      - if: github.event_name == 'pull_request' && steps.release.outputs.tag != ''
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        with:
          header: release
          recreate: true
          message: |
            ## [${{ steps.release.outputs.tag }}](${{ steps.release.outputs.url }})

            ${{ steps.release.outputs.body }}
