name: Manual Release Nag

on:
  workflow_call:

jobs:
  nag:
    if: startsWith(github.ref, 'refs/tags') && github.event.pusher.name != 'web3-bot'
    runs-on: ubuntu-latest
    name: All
    steps:
      - id: tag
        run: echo "name=${GITHUB_REF#refs/tags/}" | tee -a "$GITHUB_OUTPUT"
      - name: create an issue
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_EVENT_PUSHER_NAME: ${{ github.event.pusher.name }}
          TITLE: manual release created (${{ steps.tag.outputs.name }})
          BODY: |
            @${{ github.event.pusher.name }} just pushed a release tag: ${{ steps.tag.outputs.name }}.
            Please manually verify validity (using [`gorelease`](https://pkg.go.dev/golang.org/x/exp/cmd/gorelease)), and update `version.json` to reflect the manually released version, if necessary.
            In the future, please use the [automated process](https://github.com/ipdxco/unified-github-workflows/blob/master/VERSIONING.md).
        run: |
          gh issue create --title="$TITLE" --assignee="$GITHUB_EVENT_PUSHER_NAME" --body="$BODY" --repo="$GITHUB_REPOSITORY"
